version: "3.9"
services:
  ros-net:
    image: ros:galactic
    tty: true # use terminal, i.e. the `-t` flag
    stdin_open: true # allow terminal input, i.e. the `-i` flag
  ros-net2:
    image: ros:galactic
    tty: true # use terminal, i.e. the `-t` flag
    stdin_open: true # allow terminal input, i.e. the `-i` flag
networks:
  default:
    name: "my-overlay-net"
    external: true
